### ISSUE TITLE
你好,我这边配置了 session_token ,启动失败

### ISSUE THREAD

**Issue by Dssssds** [hcfyapp/plugin-chatgpt#1]
*  chat.openai.com 页面里面可以正常对话. 
*  F12, 找到了对应的 token ,配置了环境变量但是提示 无效的 token
* 如图
![image](https://user-images.githubusercontent.com/17268259/230728457-45222775-dc2a-4354-bde1-264646e9c007.png)
![image](https://user-images.githubusercontent.com/17268259/230728466-cadbdedb-b530-42bc-a90f-fbf3f8cdc7da.png)

**Comment by lmk123** [comment]
这个项目已经不再维护了。划词翻译刚刚发布的 v9.8.0 版本已经支持无需填写 api key 就可以直接使用 ChatGPT 了。

**Comment by Dssssds** [comment]
好嘞,谢谢啦.
